all: *.tex
	pdflatex ps-ass2Rep.tex 
	pdflatex ps-ass2Rep.tex 
	pdflatex ps-ass2Rep.tex 
#	latex ps-ass1Rep.tex
#	bibtex ps-ass1Rep
#	latex ps-ass1Rep.tex
#	latex ps-ass1Rep.tex
#	dvipdf ps-ass1Rep.dvi
	cp ps-ass2Rep.pdf ../
	xpdf ps-ass2Rep.pdf

clean:
	rm -rf *.toc *.aux *.log
	
